testname: Instrumental Similarity ABX Test
testId: test_20240229
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: get_set_num
  content: <li>クラウドワークスIDを入力し、確定したのちに、"被験者番号発行"ボタンを押してください。（IDを入力し確定を押さないと被験者番号発行ボタンを押すことはできません。）</li> <li>表示された実験URLにアクセスし、実験を開始してください。</li><li>【注意】実験URLを複数回発行することはできません。必ず一度URLを表示したらそのURLから実験を行なってください。（万が一、すでにURLを発行してしまったが今すぐに実験を開始できない場合は、発行したURLを保存し、後からそのURLにアクセスして実験を開始してください。）</li>
  id: first_page
  name: Welcome