testname: Instrumental Similarity ABX Test
testId: mini-test_0212
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: get_set_num
  content: 以下の番号をメモしてください．
  id: first_page
  name: Welcome