testname: Instrumental Similarity ABX Test
testId: mini-test_0212
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  content: 楽器音類似度に関する評価実験にご参加いただきありがとうございます.<br> 実験終了後に，支払いのためのクラウドワークスIDの入力を求められますので，忘れずにご記入ください．
  id: first_page
  name: Welcome
- type: enquete
  content: <li>最初にアンケートのご協力をお願いいたします。</li> <li>何か演奏することができる楽器がありますか？</li>
  id: enq
  name: 楽器演奏に関するアンケート
- type: generic
  content: '<li>3つの楽器音Reference,A,Bを順番に聴いてください<br> <b>楽器音は全て必ず最後まで聞いてください</b> </li>
    <li>その下に列挙された3つの要素（音色、リズム、メロディ）においてそれぞれ、<br> Referenceが<b>BよりA</b>に<b>強く近い</b>と感じる場合は<b>A+</b>を、<b>少し近い</b>と感じる場合は<b>A-</b>回答してください。<br>
    Referenceが<b>AよりB</b>に<b>強く近い</b>と感じる場合は<b>B+</b>を、<b>少し近い</b>と感じる場合は<b>B-</b>回答してください。<br>
    <b>再生した楽器音がその要素を持たない（例: ドラム音にメロディがない）場合は、N/Aを選択してください。</b><br> また、A,Bどちらも同じくらいReferenceと似ている/似ていない場合もN/Aを選択することができますが、<b>3つの要素全てにおいてN/Aという回答はできません</b>。<br>
    </li> <li> 総合的に判断してReferenceはAとBのどちらに近いかを、上記と同様に+と-を含めた4択から選択してください。<b>"総合"では真ん中は選択できません。</b></li>
    <li>選択を終えたら"Next"ボタンを押し、次の実験に進んで下さい。</li>'
  id: Top_page
  name: '実験手順（必ず最後までお読みください）'
- type: volume
  content: 音量を調整してください．このサンプルはベース音の例です.
  id: vol
  name: 音量調整
  defaultVolume: 0.5
  stimulus: configs/2024sp/resources/samples/voleme_sample.wav
- type: paired_comparison_changed
  id: ABX
  name: Instrumental Similarity Test
  content: '<li>3つの楽器音Reference,A,Bを順番に聴いてください<br> <b>楽器音は全て必ず最後まで聞いてください</b> </li>
    <li>その下に列挙された3つの要素（音色、リズム、メロディ）においてそれぞれ、<br> Referenceが<b>BよりA</b>に<b>強く近い</b>と感じる場合は<b>A+</b>を、<b>少し近い</b>と感じる場合は<b>A-</b>回答してください。<br>
    Referenceが<b>AよりB</b>に<b>強く近い</b>と感じる場合は<b>B+</b>を、<b>少し近い</b>と感じる場合は<b>B-</b>回答してください。<br>
    <b>再生した楽器音がその要素を持たない（例: ドラム音にメロディがない）場合は、N/Aを選択してください。</b><br> また、A,Bどちらも同じくらいReferenceと似ている/似ていない場合もN/Aを選択することができますが、<b>3つの要素全てにおいてN/Aという回答はできません</b>。<br>
    </li> <li> 総合的に判断してReferenceはAとBのどちらに近いかを、上記と同様に+と-を含めた4択から選択してください。<b>"総合"では真ん中は選択できません。</b></li>
    <li>選択を終えたら"Next"ボタンを押し、次の実験に進んで下さい。</li>'
  showWaveform: true
  enableLooping: false
  reference:
    X1: configs/2024sp/resources/set0/drums/0/X_2088-17.wav
    X2: configs/2024sp/resources/set0/bass/0/X_2088-29.wav
  sampleA:
    A1: configs/2024sp/resources/set0/drums/0/Y_2088-35.wav
    A2: configs/2024sp/resources/set0/bass/0/Y_2088-10.wav
  sampleB:
    B1: configs/2024sp/resources/set0/drums/0/C_2088-37.wav
    B2: configs/2024sp/resources/set0/bass/0/C_2088-51.wav
- type: finish
  name: Thank you
  content: Thank you for attending
  showResults: true
  writeResults: true
