# test config AB test, waveform, 3 conditions, no looping


testname: Instrumental Similarity ABX Test
testId: abx_noloop_changed
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: paired_comparison_changed
      id: ABX_4Q_5A
      name: Instrumental Similarity Test
      content: '<li>初めに一番上にある楽器音を聴いて下さい。これをSound Xとします。<br>
                続けて、下2つの楽器音A,Bも聴いてください<br>
                <b>楽器音は全て必ず最後まで聞いてください</b>
            </li>
            <li>そして、その下に列挙された3つの要素（音色、リズム、メロディ）においてそれぞれ、<b>XはAとBのどちらに近いか</b>を、<b>Xの位置を選択することで</b>回答してください。<br>
                例えば、<b>A</b>に近いと<b>強く</b>感じる場合は、<b>一番左</b>のボタンを選択してください。<b>B</b>に近いと<b>少し</b>感じる場合は<b>右から2番目</b>のボタンを選択してください。<br>
                <b>再生した楽器音がその要素を持たない（例: ドラム音にメロディがない）場合は、選択を真ん中から動かす必要はありません。</b><br>
                また、A,Bどちらも同じくらいXと似ている/似ていない場合も真ん中を選択することができますが、<b>3つの要素全てにおいて真ん中という回答はできません</b>。<br>

            </li>
            <li>選択を終えたら"next"ボタンを押し、次の実験に進んで下さい。</li>'
      showWaveform: true
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav


    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: true
      writeResults: true
