testname: Instrumental Similarity ABX Test
testId: inst_sim_abx_2024sp
setno: 189
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  content: 楽器音類似度に関する評価実験にご参加いただきありがとうございます。<br> 実験終了後に再度、支払いのためのクラウドワークスIDの入力を求められますので、忘れずにご記入ください。
  id: first_page
  name: Welcome
- type: generic
  content: '<li>3つの楽器音Reference,A,Bを順番に聴いてください。<br> <b>楽器音は全て必ず最後まで聞いてください。</b> </li>
    <li>その下に列挙された3つの要素（音色、リズム、メロディ）においてそれぞれ、<br> Referenceが<b>BよりA</b>に<b>強く近い</b>と感じる場合は<b>A+</b>を、<b>少し近い</b>と感じる場合は<b>A-</b>回答してください。<br>
    Referenceが<b>AよりB</b>に<b>強く近い</b>と感じる場合は<b>B+</b>を、<b>少し近い</b>と感じる場合は<b>B-</b>回答してください。<br>
    <b>再生した楽器音がその要素を持たない（例: ドラム音にメロディがない）場合は、N/Aを選択してください。</b><br> また、A,Bどちらも同じくらいReferenceと似ている/似ていない場合もN/Aを選択することができますが、<b>3つの要素全てにおいてN/Aという回答はできません</b>。<br>
    </li> <li> 総合的に判断してReferenceはAとBのどちらに近いかを、上記と同様に+と-を含めた4択から選択してください。<b>"総合"では真ん中は選択できません。</b></li>
    <li>選択を終えたら"Next"ボタンを押し、次の実験に進んで下さい。</li> <li><b>3つの楽器音全てを再生してから回答を選択しないとNextボタンは押せません。</b></li>'
  id: Top_page
  name: 実験手順の説明(必ず最後まで読んでから次へ進んでください。)
- type: volume
  content: 音量を調整してください。このサンプルはベース音の例です。
  id: vol
  name: 音量調整
  defaultVolume: 0.5
  stimulus: configs/2024sp/resources/samples/voleme_sample.wav
- type: paired_comparison_changed
  id: ABX
  setno: 189
  name: Instrumental Similarity Test
  content: '<li>3つの楽器音Reference,A,Bを順番に聴いてください。<br> <b>楽器音は全て必ず最後まで聞いてください。</b> </li>
    <li>その下に列挙された3つの要素（音色、リズム、メロディ）においてそれぞれ、<br> Referenceが<b>BよりA</b>に<b>強く近い</b>と感じる場合は<b>A+</b>を、<b>少し近い</b>と感じる場合は<b>A-</b>回答してください。<br>
    Referenceが<b>AよりB</b>に<b>強く近い</b>と感じる場合は<b>B+</b>を、<b>少し近い</b>と感じる場合は<b>B-</b>回答してください。<br>
    <b>再生した楽器音がその要素を持たない（例: ドラム音にメロディがない）場合は、N/Aを選択してください。</b><br> また、A,Bどちらも同じくらいReferenceと似ている/似ていない場合もN/Aを選択することができますが、<b>3つの要素全てにおいてN/Aという回答はできません</b>。<br>
    </li> <li> 総合的に判断してReferenceはAとBのどちらに近いかを、上記と同様に+と-を含めた4択から選択してください。<b>"総合"では真ん中は選択できません。</b></li>
    <li>選択を終えたら"Next"ボタンを押し、次の実験に進んで下さい。</li> <li><b>3つの楽器音全てを再生してから回答を選択しないとNextボタンは押せません。</b></li>'
  showWaveform: false
  enableLooping: false
  reference:
    X1: configs/2024sp/resources/set9/drums/0/X_1931-44.wav
    X2: configs/2024sp/resources/set9/bass/0/X_1931-2.wav
    X3: configs/2024sp/resources/set9/piano/0/X_1931-42.wav
    X4: configs/2024sp/resources/set9/guitar/0/X_1931-3.wav
    X5: configs/2024sp/resources/set9/residuals/0/X_1931-8.wav
    X6: configs/2024sp/resources/set9/drums/0/X_1931-44.wav
    X7: configs/2024sp/resources/set9/bass/0/X_1931-2.wav
    X8: configs/2024sp/resources/set9/piano/0/X_1931-42.wav
    X9: configs/2024sp/resources/set9/guitar/0/X_1931-3.wav
    X10: configs/2024sp/resources/set9/residuals/0/X_1931-8.wav
    X11: configs/2024sp/resources/set9/drums/1/X_1950-25.wav
    X12: configs/2024sp/resources/set9/bass/1/X_1950-6.wav
    X13: configs/2024sp/resources/set9/piano/1/X_1950-5.wav
    X14: configs/2024sp/resources/set9/guitar/1/X_1950-20.wav
    X15: configs/2024sp/resources/set9/residuals/1/X_1950-39.wav
    X16: configs/2024sp/resources/set9/drums/1/X_1950-25.wav
    X17: configs/2024sp/resources/set9/bass/1/X_1950-6.wav
    X18: configs/2024sp/resources/set9/piano/1/X_1950-5.wav
    X19: configs/2024sp/resources/set9/guitar/1/X_1950-20.wav
    X20: configs/2024sp/resources/set9/residuals/1/X_1950-39.wav
    X21: configs/2024sp/resources/set9/drums/2/X_1907-32.wav
    X22: configs/2024sp/resources/set9/bass/2/X_1907-36.wav
    X23: configs/2024sp/resources/set9/piano/2/X_1907-29.wav
    X24: configs/2024sp/resources/set9/guitar/2/X_1907-23.wav
    X25: configs/2024sp/resources/set9/residuals/2/X_1907-21.wav
    X26: configs/2024sp/resources/set9/drums/2/X_1907-32.wav
    X27: configs/2024sp/resources/set9/bass/2/X_1907-36.wav
    X28: configs/2024sp/resources/set9/piano/2/X_1907-29.wav
    X29: configs/2024sp/resources/set9/guitar/2/X_1907-23.wav
    X30: configs/2024sp/resources/set9/residuals/2/X_1907-21.wav
    X31: configs/2024sp/resources/set9/drums/3/X_1968-27.wav
    X32: configs/2024sp/resources/set9/bass/3/X_1968-40.wav
    X33: configs/2024sp/resources/set9/piano/3/X_1968-25.wav
    X34: configs/2024sp/resources/set9/guitar/3/X_1968-46.wav
    X35: configs/2024sp/resources/set9/residuals/3/X_1968-35.wav
    X36: configs/2024sp/resources/set9/drums/3/X_1968-27.wav
    X37: configs/2024sp/resources/set9/bass/3/X_1968-40.wav
    X38: configs/2024sp/resources/set9/piano/3/X_1968-25.wav
    X39: configs/2024sp/resources/set9/guitar/3/X_1968-46.wav
    X40: configs/2024sp/resources/set9/residuals/3/X_1968-35.wav
    X41: configs/2024sp/resources/samples/dummyX1.wav
    X42: configs/2024sp/resources/samples/dummyX2.wav
  sampleA:
    A1: configs/2024sp/resources/set9/drums/0/C_1882-26.wav
    A2: configs/2024sp/resources/set9/bass/0/C_1882-2.wav
    A3: configs/2024sp/resources/set9/piano/0/Y_1931-44.wav
    A4: configs/2024sp/resources/set9/guitar/0/C_1882-9.wav
    A5: configs/2024sp/resources/set9/residuals/0/C_1882-13.wav
    A6: configs/2024sp/resources/set9/drums/0/A_1897-45.wav
    A7: configs/2024sp/resources/set9/bass/0/A_1897-43.wav
    A8: configs/2024sp/resources/set9/piano/0/A_1897-45.wav
    A9: configs/2024sp/resources/set9/guitar/0/A_1897-3.wav
    A10: configs/2024sp/resources/set9/residuals/0/A_1897-53.wav
    A11: configs/2024sp/resources/set9/drums/1/C_2079-33.wav
    A12: configs/2024sp/resources/set9/bass/1/C_2079-23.wav
    A13: configs/2024sp/resources/set9/piano/1/C_2079-7.wav
    A14: configs/2024sp/resources/set9/guitar/1/C_2079-30.wav
    A15: configs/2024sp/resources/set9/residuals/1/Y_1950-13.wav
    A16: configs/2024sp/resources/set9/drums/1/A_1876-29.wav
    A17: configs/2024sp/resources/set9/bass/1/A_1876-41.wav
    A18: configs/2024sp/resources/set9/piano/1/A_1876-21.wav
    A19: configs/2024sp/resources/set9/guitar/1/A_1876-9.wav
    A20: configs/2024sp/resources/set9/residuals/1/A_1876-7.wav
    A21: configs/2024sp/resources/set9/drums/2/Y_1907-46.wav
    A22: configs/2024sp/resources/set9/bass/2/Y_1907-15.wav
    A23: configs/2024sp/resources/set9/piano/2/Y_1907-41.wav
    A24: configs/2024sp/resources/set9/guitar/2/C_2082-4.wav
    A25: configs/2024sp/resources/set9/residuals/2/C_2082-9.wav
    A26: configs/2024sp/resources/set9/drums/2/A_1986-15.wav
    A27: configs/2024sp/resources/set9/bass/2/A_1986-52.wav
    A28: configs/2024sp/resources/set9/piano/2/A_1986-7.wav
    A29: configs/2024sp/resources/set9/guitar/2/A_1986-53.wav
    A30: configs/2024sp/resources/set9/residuals/2/A_1986-7.wav
    A31: configs/2024sp/resources/set9/drums/3/C_1927-23.wav
    A32: configs/2024sp/resources/set9/bass/3/Y_1968-7.wav
    A33: configs/2024sp/resources/set9/piano/3/Y_1968-42.wav
    A34: configs/2024sp/resources/set9/guitar/3/Y_1968-54.wav
    A35: configs/2024sp/resources/set9/residuals/3/C_1927-27.wav
    A36: configs/2024sp/resources/set9/drums/3/A_2054-16.wav
    A37: configs/2024sp/resources/set9/bass/3/A_2054-50.wav
    A38: configs/2024sp/resources/set9/piano/3/A_2054-52.wav
    A39: configs/2024sp/resources/set9/guitar/3/A_2054-24.wav
    A40: configs/2024sp/resources/set9/residuals/3/A_2054-21.wav
    A41: configs/2024sp/resources/samples/dummyX1.wav
    A42: configs/2024sp/resources/samples/dummyA2.wav
  sampleB:
    B1: configs/2024sp/resources/set9/drums/0/Y_1931-35.wav
    B2: configs/2024sp/resources/set9/bass/0/Y_1931-43.wav
    B3: configs/2024sp/resources/set9/piano/0/C_1882-53.wav
    B4: configs/2024sp/resources/set9/guitar/0/Y_1931-16.wav
    B5: configs/2024sp/resources/set9/residuals/0/Y_1931-22.wav
    B6: configs/2024sp/resources/set9/drums/0/B_2019-26.wav
    B7: configs/2024sp/resources/set9/bass/0/B_2019-52.wav
    B8: configs/2024sp/resources/set9/piano/0/B_2019-16.wav
    B9: configs/2024sp/resources/set9/guitar/0/B_2019-17.wav
    B10: configs/2024sp/resources/set9/residuals/0/B_2019-53.wav
    B11: configs/2024sp/resources/set9/drums/1/Y_1950-36.wav
    B12: configs/2024sp/resources/set9/bass/1/Y_1950-25.wav
    B13: configs/2024sp/resources/set9/piano/1/Y_1950-4.wav
    B14: configs/2024sp/resources/set9/guitar/1/Y_1950-39.wav
    B15: configs/2024sp/resources/set9/residuals/1/C_2079-14.wav
    B16: configs/2024sp/resources/set9/drums/1/B_2049-35.wav
    B17: configs/2024sp/resources/set9/bass/1/B_2049-28.wav
    B18: configs/2024sp/resources/set9/piano/1/B_2049-33.wav
    B19: configs/2024sp/resources/set9/guitar/1/B_2049-20.wav
    B20: configs/2024sp/resources/set9/residuals/1/B_2049-25.wav
    B21: configs/2024sp/resources/set9/drums/2/C_2082-5.wav
    B22: configs/2024sp/resources/set9/bass/2/C_2082-34.wav
    B23: configs/2024sp/resources/set9/piano/2/C_2082-12.wav
    B24: configs/2024sp/resources/set9/guitar/2/Y_1907-12.wav
    B25: configs/2024sp/resources/set9/residuals/2/Y_1907-34.wav
    B26: configs/2024sp/resources/set9/drums/2/B_1952-24.wav
    B27: configs/2024sp/resources/set9/bass/2/B_1952-12.wav
    B28: configs/2024sp/resources/set9/piano/2/B_1952-31.wav
    B29: configs/2024sp/resources/set9/guitar/2/B_1952-26.wav
    B30: configs/2024sp/resources/set9/residuals/2/B_1952-36.wav
    B31: configs/2024sp/resources/set9/drums/3/Y_1968-41.wav
    B32: configs/2024sp/resources/set9/bass/3/C_1927-32.wav
    B33: configs/2024sp/resources/set9/piano/3/C_1927-12.wav
    B34: configs/2024sp/resources/set9/guitar/3/C_1927-20.wav
    B35: configs/2024sp/resources/set9/residuals/3/Y_1968-30.wav
    B36: configs/2024sp/resources/set9/drums/3/B_1981-42.wav
    B37: configs/2024sp/resources/set9/bass/3/B_1981-31.wav
    B38: configs/2024sp/resources/set9/piano/3/B_1981-18.wav
    B39: configs/2024sp/resources/set9/guitar/3/B_1981-30.wav
    B40: configs/2024sp/resources/set9/residuals/3/B_1981-26.wav
    B41: configs/2024sp/resources/samples/dummyB1.wav
    B42: configs/2024sp/resources/samples/dummyX2.wav
- type: enquete
  content: <li>最後にアンケートのご協力をお願いいたします。</li> <li>何か演奏することができる楽器がありますか？</li>
  id: enq
  name: 楽器演奏に関するアンケート
- type: finish
  name: Thank you
  content: ご協力ありがとうございました！.<br> <b>支払いのため、以下にクラウドワークスIDの入力をお願いします。<b>
  questionnaire:
  - label: Worker Id
    name: workerId
    type: text
  showResults: false
  writeResults: true
